# NumPy 入门

In [6]:
# 比较ndarray和list
# ndarray普遍比list快数倍乃至数十倍
import numpy as np
my_arr = np.arange(100_0000)
my_list = list(range(100_0000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = my_list * 2

1.11 ms ± 24.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
14.9 ms ± 236 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### ndarray N维数组对象

In [11]:
array = np.array([[1, -3, 2.5, -1.7], [2, 19, -8.3, -2]])
print(array)
print(type(array))
print(array * 10)
print(array + array)
# 属性
print(array.shape) # 维度
print(array.dtype) # 元素类型

[[ 1.  -3.   2.5 -1.7]
 [ 2.  19.  -8.3 -2. ]]
<class 'numpy.ndarray'>
[[ 10. -30.  25. -17.]
 [ 20. 190. -83. -20.]]
[[  2.   -6.    5.   -3.4]
 [  4.   38.  -16.6  -4. ]]
(2, 4)
float64


In [24]:
# 特殊创建方法
# 无之、全0、全1数组
print(np.empty(shape=(1, 2)))
print(np.zeros((3, 2), dtype='int32'))
print(np.ones((4,4)))
print(np.full((3, 3), 2))
# 创建类似的全0/empty/全1数组
print(">>>>>===========<<<<<")
shape_list = [[2,3], [3, 2]]
print(np.zeros_like(shape_list))
print(np.ones_like(shape_list))
print(np.empty_like(shape_list))

[[6.36598737e-314 4.24399158e-314]]
[[0 0]
 [0 0]
 [0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
>>>>>===========<<<<<
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[2 3]
 [3 2]]


In [20]:
# 转换
l1 = [1, 2, 3]
print(np.asarray(l1))

[1 2 3]


In [41]:
# 大小相同的数组的运算，将会传递到每一个元素上
arr_cals = np.full((3, 3), 10, np.int32)
print(arr_cals)
print(arr_cals / 200)
# 大小不同的数组之间的运算触发广播，广播会自动对齐（按列或按行）
arr_cals2 = np.full((1, 3), 2, dtype=np.int32)
print(arr_cals * arr_cals2)
arr_cals3 = np.full((3, 1), 10, dtype=np.int32)
print(arr_cals * arr_cals3)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[0.05 0.05 0.05]
 [0.05 0.05 0.05]
 [0.05 0.05 0.05]]
[[20 20 20]
 [20 20 20]
 [20 20 20]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [64]:
# 访问单个元素的特殊方式
arr2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(arr2d[1][2])
print(arr2d[1, 2])
# 单个索引操作的传播
arr2d[0] = 12
print(arr2d)
# 切片
print(arr2d[0][0:2])
print(arr2d[:2, :1]) # 第一列的前两行

# 比较的传递
print(arr2d == 12)

6
6
[[12 12 12]
 [ 4  5  6]]
[12 12]
[[12]
 [ 4]]
[[ True  True  True]
 [False False False]]


In [66]:
# 花式索引
arr2d3r=np.array([[1, 2, 3], [3,4, 5], [6,7,8]])
print(arr2d3r[[-1, -3]]) # 索引n行

[[6 7 8]
 [1 2 3]]


In [69]:
# 转置与轴对换
arr = np.arange(15).reshape(3, 5)
print(arr)
# 轴对换，即行列对换，行变列，列变行
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### 通用元素级数组函数


In [71]:
arr_func = np.arange(10)
print(np.sqrt(arr_func))
print(np.exp(arr_func))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [81]:
# 保存与加载
arr_save = np.arange(15).reshape(5, 3)
np.save('save_data', arr_save) # 存的是二进制
read_data = np.load('./save_data.npy')
print(read_data)
# np.savez可以保存多个数组，读取时为字典形式

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
